name: Indieapex
favicon: null
layout_spectrum: 0.20331042679026723
typography_spectrum: 0.7294351870659739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6996065119747072
  lightness: 0.9926301632076502
  saturation: 0.31145968777127564
  rhythmicContrast: 0.6650869539007545
purpose: []
